apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: my-namespace

resources:
- deployment.yaml

patchesStrategicMerge:
# - resource_patch.yaml

images:
  - name: busybox
    newTag: "1.27"
