name: DummyCheck

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: install aqua
        uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.19.2
